// Datos reales del tarifario New Trips · Mayo 2026 → Abril 2027
// Hoy es 20 de mayo de 2026.

window.NT_PACKAGES = [
  // ============ MAYO - JUNIO 2026 ============
  {
    id: "cataratas-posadas-federacion-mayo",
    destinos: ["cataratas", "federacion"],
    titulo: "Cataratas · Posadas · Federación",
    subtitulo: "Triple destino en 8 días",
    destino: "Misiones · Entre Ríos",
    categoria: "cataratas",
    transporte: "bus",
    duracion: "8 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel El Carmen 3★",
    regimen: "Media pensión (desayuno y cena, sin bebidas)",
    excursiones: [
      "Ruinas de San Ignacio*", "Minas de Wanda*", "Cataratas Argentinas*", "Cataratas Brasileras*",
      "Aripuca*", "Visita a yerbatera", "City Tour Puerto Iguazú + Hito 3 Fronteras",
      "Duty Free Shop", "Costanera de Posadas", "Full Day Termas de Federación*"
    ],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "07 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Cena Show en Posadas (al regreso)", "Cena a bordo con bebidas (ida)", "Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada"],
    promo2do: "50% OFF",
    precio: 579999,
    precioCama: 609999,
    precio2do: 289999,
    precio2doCama: 304999,
    base: "doble",
    sellos: ["promo-2x1", "viaja-solo"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["mayo-junio-26", "escapadas"],
  },
  {
    id: "merlo-mayo",
    titulo: "Escapada a Merlo",
    subtitulo: "Sierras de San Luis · Piscina climatizada",
    destino: "Merlo · San Luis",
    categoria: "sierras",
    transporte: "bus",
    duracion: "5 días · 3 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Flamingo (Piscina climatizada)",
    regimen: "Media pensión (desayuno y cena, sin bebidas)",
    excursiones: ["City Tour en Merlo", "Visita al Dique Piscu Yaco"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "21 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "Tarifa PROMO desde el origen · cupos limitados"],
    precio: 269999,
    precioCama: 299999,
    base: "doble",
    sellos: ["promo-puntual", "piscina-climatizada", "viaja-solo"],
    color: "#A36B2E",
    foto: "merlo",
    temporadas: ["mayo-junio-26", "escapadas", "finde-xl", "promociones"],
  },
  {
    id: "mendoza-cacheuta-sanrafael-mayo",
    titulo: "Mendoza · Cacheuta · San Rafael",
    subtitulo: "Bodegas, termas y montaña · Promo 3x2",
    destino: "Mendoza",
    categoria: "sierras",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel Cordón del Plata (Mendoza) + 3n Hotel San Rafael",
    regimen: "Media pensión (desayuno y cena, sin bebidas)",
    excursiones: ["City Tour Mendoza", "Visita a bodega (Mendoza)", "Termas de Cacheuta*", "Bodega y aceitera (San Rafael)"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "21 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada"],
    promo2do: "30% OFF",
    precio: 599999,
    precioCama: 619999,
    precio2do: 419999,
    base: "doble",
    sellos: ["promo-2do-30", "viaja-solo"],
    color: "#7C2418",
    foto: "mendoza",
    temporadas: ["mayo-junio-26", "promociones"],
  },
  {
    id: "salta-jujuy-junio",
    titulo: "Norte Argentino",
    subtitulo: "Salta y Jujuy · Quebrada de Humahuaca",
    destino: "Salta · Jujuy",
    categoria: "sierras",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "3n Hotel Las Vegas (Salta) + 2n Hotel Augustus (Jujuy)",
    regimen: "Media pensión",
    excursiones: ["City Tour Salta", "Tilcara", "Quebrada de Humahuaca"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "11 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    promo2do: "50% OFF",
    precio: 849999,
    precioCama: 869999,
    precio2do: 424999,
    base: "doble",
    sellos: ["promo-2x1", "viaja-solo"],
    color: "#B8451F",
    foto: "salta",
    temporadas: ["mayo-junio-26"],
  },
  {
    id: "rio-hondo-mayo",
    titulo: "Termas de Río Hondo",
    subtitulo: "9 días con pensión completa",
    destino: "Santiago del Estero",
    categoria: "termas",
    transporte: "bus",
    duracion: "9 días · 6 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Paraíso Termal 2★",
    regimen: "Pensión completa (sin bebidas)",
    excursiones: ["City Tour en Río Hondo"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "04 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 499999,
    precioCamaPromo: 529999,
    precio: 549999,
    precioCama: 579999,
    promo: "Pago contado",
    promoDescuento: "9% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "oferta", "pension-completa", "viaja-solo"],
    color: "#B8451F",
    foto: "termas",
    temporadas: ["mayo-junio-26", "promociones", "escapadas"],
  },
  {
    id: "carlos-paz-mayo",
    titulo: "Villa Carlos Paz",
    subtitulo: "Sierras de Córdoba · Piscina climatizada",
    destino: "Córdoba",
    categoria: "sierras",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Embajador (Piscina climatizada)",
    regimen: "Pensión completa (sin bebidas)",
    excursiones: ["Cosquín y La Falda", "Visita a fábrica de alfajores", "Recorrido por Córdoba Capital"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "14 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Promo 2do pasajero aplica sobre la 2da plaza en la misma reserva"],
    promo2do: "50% OFF",
    precio: 419999,
    precioCama: 439999,
    precio2do: 209999,
    base: "doble",
    sellos: ["promo-2x1", "pension-completa", "piscina-climatizada"],
    color: "#446B2E",
    foto: "carlospaz",
    temporadas: ["mayo-junio-26", "promociones"],
  },
  {
    id: "federacion-bus-cama-junio",
    titulo: "Federación · Bus Cama",
    subtitulo: "Termas de Entre Ríos · Bus 100% cama",
    destino: "Entre Ríos",
    categoria: "termas",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "100% Coche Cama (ambos pisos)",
    hotel: "Hotel Clima Termal Suites",
    regimen: "Desayuno. Opcional MP en Los Pinos $99.999",
    excursiones: ["Termas de Chajarí*", "Termas de Concepción*", "Visita a fábrica de alfajores"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "20 Jun 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio a bordo", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada"],
    promo2do: "50% OFF",
    precioCama: 489999,
    precio2do: 244999,
    base: "doble",
    sellos: ["promo-2x1", "viaja-solo"],
    destacado: "Bus 100% Coche Cama",
    color: "#B8451F",
    foto: "federacion",
    temporadas: ["mayo-junio-26", "escapadas"],
  },

  // ============ VACACIONES DE INVIERNO · JULIO 2026 ============
  {
    id: "cataratas-brasilero-julio",
    destinos: ["cataratas-brasil", "federacion"],
    titulo: "Cataratas con Posadas",
    subtitulo: "Lado Brasilero · Piscina climatizada",
    destino: "Foz do Iguaçu · Brasil",
    categoria: "cataratas",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Dom Pedro 3★ (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: [
      "Ruinas de San Ignacio*", "Minas de Wanda*", "Cataratas Argentinas*", "Cataratas Brasileras*",
      "Aripuca*", "Yerbatera", "City Tour Puerto Iguazú + Hito 3 Fronteras",
      "Duty Free Shop", "Costanera de Posadas", "Full Day Termas de Federación*"
    ],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "18 Jul 2026", estado: "ultimos-cupos" },
      { fecha: "26 Jul 2026", estado: "disponible" },
    ],
    incluye: ["Cena Show en Posadas (al regreso)", "Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada"],
    precio: 749999,
    precioCama: 769999,
    precioAntes: 839999,
    base: "doble",
    familyPlan: { menorHasta5: 449999, menor6a10: 599999 },
    sellos: ["family-plan", "piscina-climatizada", "ultimos-cupos"],
    color: "#0F6E3F",
    foto: "cataratas-brasil",
    temporadas: ["vacaciones-invierno", "brasil"],
  },
  {
    id: "cataratas-argentino-julio",
    destinos: ["cataratas", "federacion"],
    titulo: "Cataratas con Posadas",
    subtitulo: "Lado Argentino · Vacaciones de invierno",
    destino: "Puerto Iguazú · Misiones",
    categoria: "cataratas",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Carmen 3★",
    regimen: "Media pensión",
    excursiones: [
      "Ruinas de San Ignacio*", "Minas de Wanda*", "Cataratas Argentinas*", "Cataratas Brasileras*",
      "Aripuca*", "Yerbatera", "City Tour Puerto Iguazú + Hito 3 Fronteras",
      "Duty Free Shop", "Costanera de Posadas", "Full Day Termas de Federación*"
    ],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "18 Jul 2026", estado: "ultimos-cupos" },
      { fecha: "22 Jul 2026", estado: "disponible" },
      { fecha: "26 Jul 2026", estado: "disponible" },
    ],
    incluye: ["Cena Show en Posadas (al regreso)", "Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada", "Nueva fecha 22 Jul: Coche Cama $699.999"],
    precio: 649999,
    precioCama: 699999,
    precioAntes: 729999,
    base: "doble",
    familyPlan: { menorHasta5: 499999 },
    sellos: ["family-plan", "ultimos-cupos"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["vacaciones-invierno"],
  },
  {
    id: "mendoza-cacheuta-julio",
    titulo: "Mendoza con Termas de Cacheuta",
    subtitulo: "Vacaciones de invierno",
    destino: "Mendoza",
    categoria: "sierras",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Cordón del Plata (Mendoza)",
    regimen: "Media pensión",
    excursiones: ["City Tour Mendoza", "Visita a bodega", "Termas de Cacheuta*", "Alta Montaña"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "19 Jul 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["* No incluye entrada"],
    precio: 659999,
    precioCama: 679999,
    base: "doble",
    sellos: ["viaja-solo"],
    color: "#7C2418",
    foto: "mendoza",
    temporadas: ["vacaciones-invierno"],
  },
  {
    id: "salta-jujuy-julio",
    titulo: "Salta y Jujuy con Humahuaca",
    subtitulo: "Vacaciones de invierno · Norte Argentino",
    destino: "Salta · Jujuy",
    categoria: "sierras",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "3n Hotel Las Vegas (Salta) + 2n Hotel Augustus (Jujuy)",
    regimen: "Media pensión",
    excursiones: ["City Tour Salta", "Tilcara", "Quebrada de Humahuaca"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "21 Jul 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    precio: 899999,
    precioCama: 929999,
    base: "doble",
    sellos: ["viaja-solo"],
    color: "#B8451F",
    foto: "salta",
    temporadas: ["vacaciones-invierno"],
  },
  {
    id: "carlos-paz-julio",
    titulo: "Villa Carlos Paz",
    subtitulo: "Vacaciones de invierno · Pensión completa",
    destino: "Córdoba",
    categoria: "sierras",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Embajador (Piscina climatizada)",
    regimen: "Pensión completa",
    excursiones: ["Cosquín y La Falda", "Visita a fábrica de alfajores", "Córdoba Capital"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "26 Jul 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    precio: 499999,
    precioCama: 519999,
    base: "doble",
    sellos: ["pension-completa", "piscina-climatizada"],
    color: "#446B2E",
    foto: "carlospaz",
    temporadas: ["vacaciones-invierno"],
  },
  {
    id: "camboriu-federacion-julio",
    destinos: ["camboriu", "federacion"],
    titulo: "Camboriú con Federación",
    subtitulo: "Vacaciones de invierno · Brasil",
    destino: "Balneario Camboriú · Brasil",
    categoria: "playa",
    transporte: "bus",
    duracion: "12 días · 7 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Hamburgo (Piscina climatizada) — Camboriú",
    regimen: "Desayuno o media pensión (a elección)",
    excursiones: ["Itaipú", "Blumenau Paseo de Compras", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy", "Liniers", "Zárate"],
    salidas: [
      { fecha: "18 Jul 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica", "* No incluye entrada"],
    precio: 899999,
    precioCama: 929999,
    precioMP: 999999,
    precioCamaMP: 1029999,
    base: "doble",
    sellos: ["piscina-climatizada"],
    color: "#1B7A8E",
    foto: "camboriu",
    temporadas: ["vacaciones-invierno", "brasil"],
  },
  {
    id: "salta-aereo-julio",
    titulo: "Salta en Aéreo",
    subtitulo: "Vuelo + hotel + Tren a las Nubes",
    destino: "Salta",
    categoria: "aereos",
    transporte: "aereo",
    aerolinea: "Aerolíneas Argentinas",
    duracion: "5 días · 4 noches",
    hotel: "Hotel Las Vegas (Salta)",
    regimen: "Desayuno + media pensión incluida",
    excursiones: ["City Tour Salta", "Tilcara", "Quebrada de Humahuaca", "Tren a las Nubes"],
    embarques: ["Vuelo desde Buenos Aires (bolso de mano + carry on)"],
    salidas: [
      { fecha: "18 Jul 2026", estado: "cupos-confirmados" },
      { fecha: "26 Jul 2026", estado: "cupos-confirmados" },
    ],
    incluye: ["Tickets aéreos Aerolíneas Argentinas", "Traslado aeropuerto/hotel/aeropuerto", "Coordinador permanente", "Cupos confirmados"],
    precio: 749999,
    base: "doble",
    sellos: ["cupos-confirmados"],
    destacado: "Incluye Tren a las Nubes",
    color: "#B8451F",
    foto: "salta",
    temporadas: ["vacaciones-invierno"],
  },
  {
    id: "cataratas-aereo-brasilero-julio",
    titulo: "Cataratas en Aéreo",
    subtitulo: "Lado Brasilero · Piscina climatizada",
    destino: "Foz do Iguaçu · Brasil",
    categoria: "aereos",
    transporte: "aereo",
    aerolinea: "Aerolíneas Argentinas",
    duracion: "5 días · 4 noches",
    hotel: "Hotel Dom Pedro (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: ["Cataratas Brasileras", "City Tour Foz", "Duty Free Shop"],
    embarques: ["Vuelo desde Buenos Aires"],
    salidas: [{ fecha: "21 Jul 2026", estado: "disponible" }],
    incluye: ["Tickets aéreos Aerolíneas Argentinas", "Traslado aeropuerto/hotel/aeropuerto", "Coordinador permanente"],
    precio: 849999,
    base: "doble",
    familyPlan: { menorHasta5: 549999, menor6a10: 699999 },
    sellos: ["family-plan", "piscina-climatizada"],
    color: "#0F6E3F",
    foto: "cataratas-brasil",
    temporadas: ["vacaciones-invierno", "brasil"],
  },
  {
    id: "cataratas-aereo-argentino-julio",
    titulo: "Cataratas en Aéreo",
    subtitulo: "Lado Argentino · Vacaciones de invierno",
    destino: "Puerto Iguazú",
    categoria: "aereos",
    transporte: "aereo",
    aerolinea: "Aerolíneas Argentinas",
    duracion: "5 días · 4 noches",
    hotel: "Hotel Carmen (Puerto Iguazú)",
    regimen: "Media pensión",
    excursiones: ["Cataratas Argentinas", "City Tour Puerto Iguazú", "Hito 3 Fronteras"],
    embarques: ["Vuelo desde Buenos Aires"],
    salidas: [{ fecha: "25 Jul 2026", estado: "disponible" }],
    incluye: ["Tickets aéreos Aerolíneas Argentinas", "Traslado aeropuerto/hotel/aeropuerto", "Coordinador permanente"],
    precio: 799999,
    base: "doble",
    familyPlan: { menorHasta5: 649999 },
    sellos: ["family-plan"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["vacaciones-invierno"],
  },

  // ============ AGOSTO - DICIEMBRE 2026 ============
  {
    id: "rio-hondo-agosto",
    titulo: "Termas de Río Hondo",
    subtitulo: "9 días con pensión completa",
    destino: "Santiago del Estero",
    categoria: "termas",
    transporte: "bus",
    duracion: "9 días · 6 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Paraíso Termal 2★",
    regimen: "Pensión completa",
    excursiones: ["City Tour en Río Hondo"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "04 Ago 2026", estado: "disponible" },
      { fecha: "31 Ago 2026", estado: "disponible" },
    ],
    incluye: ["Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    precio: 599999,
    precioCama: 619999,
    base: "doble",
    sellos: ["pension-completa", "viaja-solo"],
    color: "#B8451F",
    foto: "termas",
    temporadas: ["agosto-diciembre"],
  },
  {
    id: "cataratas-posadas-federacion-agosto",
    destinos: ["cataratas", "federacion"],
    titulo: "Cataratas · Posadas · Federación",
    subtitulo: "8 días con todo incluido",
    destino: "Misiones · Entre Ríos",
    categoria: "cataratas",
    transporte: "bus",
    duracion: "8 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel El Carmen 3★",
    regimen: "Media pensión",
    excursiones: [
      "Ruinas de San Ignacio*", "Minas de Wanda*", "Cataratas Argentinas*", "Cataratas Brasileras*",
      "Aripuca*", "Yerbatera", "City Tour Puerto Iguazú + Hito 3 Fronteras",
      "Duty Free Shop", "Costanera de Posadas", "Full Day Termas de Federación*"
    ],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "09 Ago 2026", estado: "disponible" },
      { fecha: "06 Sep 2026", estado: "disponible" },
      { fecha: "20 Sep 2026", estado: "disponible" },
      { fecha: "04 Oct 2026", estado: "disponible" },
      { fecha: "18 Oct 2026", estado: "disponible" },
      { fecha: "01 Nov 2026", estado: "disponible" },
      { fecha: "15 Nov 2026", estado: "disponible" },
      { fecha: "06 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena Show en Posadas (al regreso)", "Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada"],
    precio: 649999,
    precioCama: 669999,
    base: "doble",
    sellos: ["viaja-solo"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["agosto-diciembre"],
  },
  {
    id: "mendoza-cacheuta-sanrafael-agosto",
    titulo: "Mendoza · Cacheuta · San Rafael",
    subtitulo: "Bodegas y montaña · Tarifa promo",
    destino: "Mendoza",
    categoria: "sierras",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel Dakar (Mendoza) + 3n Hotel San Rafael",
    regimen: "Media pensión",
    excursiones: ["City Tour Mendoza", "Visita a bodega", "Termas de Cacheuta*", "Bodega y aceitera (San Rafael)"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "16 Ago 2026", estado: "disponible" },
      { fecha: "13 Sep 2026", estado: "disponible" },
      { fecha: "11 Oct 2026", estado: "disponible" },
      { fecha: "08 Nov 2026", estado: "disponible" },
      { fecha: "06 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 649999,
    precioCamaPromo: 669999,
    precio: 699999,
    precioCama: 719999,
    promo: "Pago contado",
    promoDescuento: "7% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "viaja-solo"],
    color: "#7C2418",
    foto: "mendoza",
    temporadas: ["agosto-diciembre", "promociones"],
  },
  {
    id: "mendoza-vinadelmar",
    destinos: ["mendoza", "vina"],
    titulo: "Mendoza · Viña del Mar",
    subtitulo: "Cordillera y Pacífico · Chile",
    destino: "Argentina · Chile",
    categoria: "internacional",
    transporte: "bus",
    duracion: "9 días · 6 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel Dakar (Mendoza) + 4n Hotel Imperial (Viña del Mar)",
    regimen: "Media pensión",
    excursiones: ["Alta Montaña", "City Tour Viña del Mar"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "01 Oct 2026", estado: "disponible" },
      { fecha: "10 Nov 2026", estado: "disponible" },
      { fecha: "04 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica", "Tarifa promo aplica con pago total al reservar"],
    precioPromo: 799999,
    precioCamaPromo: 819999,
    precio: 849999,
    precioCama: 869999,
    promo: "Pago contado",
    promoDescuento: "6% OFF",
    base: "doble",
    sellos: ["tarifa-promo"],
    color: "#1B5E8C",
    foto: "vina",
    temporadas: ["agosto-diciembre", "promociones"],
  },
  {
    id: "salta-jujuy-agosto",
    titulo: "Norte Argentino",
    subtitulo: "Salta y Jujuy · Quebrada de Humahuaca",
    destino: "Salta · Jujuy",
    categoria: "sierras",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "3n Hotel Las Vegas (Salta) + 2n Hotel Augustus (Jujuy)",
    regimen: "Media pensión",
    excursiones: ["City Tour Salta", "Tilcara", "Quebrada de Humahuaca"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "23 Ago 2026", estado: "disponible" },
      { fecha: "17 Sep 2026", estado: "disponible" },
      { fecha: "19 Oct 2026", estado: "disponible" },
      { fecha: "16 Nov 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    precio: 899999,
    precioCama: 919999,
    base: "doble",
    sellos: ["viaja-solo"],
    color: "#B8451F",
    foto: "salta",
    temporadas: ["agosto-diciembre"],
  },
  {
    id: "carlos-paz-agosto",
    titulo: "Villa Carlos Paz",
    subtitulo: "Sierras · Tarifa promo · Pensión completa",
    destino: "Córdoba",
    categoria: "sierras",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Embajador (Piscina climatizada)",
    regimen: "Pensión completa",
    excursiones: ["Cosquín y La Falda", "Visita a fábrica de alfajores", "Córdoba Capital"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "09 Ago 2026", estado: "disponible" },
      { fecha: "13 Sep 2026", estado: "disponible" },
      { fecha: "11 Oct 2026", estado: "disponible" },
      { fecha: "22 Nov 2026", estado: "disponible" },
      { fecha: "13 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 449999,
    precioCamaPromo: 469999,
    precio: 499999,
    precioCama: 519999,
    promo: "Pago contado",
    promoDescuento: "10% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "pension-completa", "piscina-climatizada"],
    color: "#446B2E",
    foto: "carlospaz",
    temporadas: ["agosto-diciembre", "promociones"],
  },
  {
    id: "camboriu-federacion-clasico-nov",
    destinos: ["camboriu", "federacion"],
    titulo: "Camboriú con Federación",
    subtitulo: "Clásico 7 noches · Brasil",
    destino: "Balneario Camboriú · Brasil",
    categoria: "playa",
    transporte: "bus",
    duracion: "12 días · 7 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Hamburgo (Piscina climatizada) — Camboriú",
    regimen: "Media pensión",
    excursiones: ["Itajaí", "Florianópolis (centro)", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy", "Liniers", "Zárate"],
    salidas: [
      { fecha: "15 Nov 2026", estado: "disponible" },
      { fecha: "01 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica", "Tarifa promo aplica con pago total al reservar"],
    precioPromo: 999999,
    precioCamaPromo: 1029999,
    precio: 1099999,
    precioCama: 1129999,
    promo: "Pago contado",
    promoDescuento: "9% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "piscina-climatizada"],
    color: "#1B7A8E",
    foto: "camboriu",
    temporadas: ["agosto-diciembre", "brasil", "promociones"],
  },
  {
    id: "camboriu-punta-federacion",
    destinos: ["camboriu", "punta-este", "federacion"],
    titulo: "Camboriú · Punta del Este · Federación",
    subtitulo: "Triple destino · Uruguay y Brasil",
    destino: "Punta del Este · Camboriú",
    categoria: "playa",
    transporte: "bus",
    duracion: "12 días · 7 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel Sunset Beach (Punta del Este) + 5n Hotel Hamburgo (Camboriú)",
    regimen: "Desayuno en Punta del Este / Media pensión en Camboriú",
    excursiones: ["City Tour Punta del Este", "Itajaí", "Florianópolis (centro)", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy", "Liniers", "Zárate"],
    salidas: [
      { fecha: "01 Oct 2026", estado: "disponible" },
      { fecha: "18 Oct 2026", estado: "disponible" },
      { fecha: "01 Nov 2026", estado: "disponible" },
      { fecha: "15 Nov 2026", estado: "disponible" },
      { fecha: "01 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica", "Tarifa promo aplica con pago total al reservar"],
    precioPromo: 999999,
    precioCamaPromo: 1029999,
    precio: 1099999,
    precioCama: 1129999,
    promo: "Pago contado",
    promoDescuento: "9% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "piscina-climatizada"],
    destacado: "3 destinos en 1 viaje",
    color: "#1B7A8E",
    foto: "punta-este",
    temporadas: ["agosto-diciembre", "brasil", "promociones"],
  },
  {
    id: "merlo-agosto",
    titulo: "Escapada a Merlo",
    subtitulo: "Sierras de San Luis · 5 días",
    destino: "Merlo · San Luis",
    categoria: "sierras",
    transporte: "bus",
    duracion: "5 días · 3 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Clima 3 (Céntrico)",
    regimen: "Media pensión",
    excursiones: ["City Tour Merlo", "Dique Piscu Yaco"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "07 Sep 2026", estado: "disponible" },
      { fecha: "11 Oct 2026", estado: "disponible" },
      { fecha: "09 Nov 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 319999,
    precioCamaPromo: 349999,
    precio: 349999,
    precioCama: 379999,
    promo: "Pago contado",
    promoDescuento: "9% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "viaja-solo"],
    color: "#A36B2E",
    foto: "merlo",
    temporadas: ["agosto-diciembre", "escapadas", "finde-xl", "promociones"],
  },
  {
    id: "federacion-agosto",
    titulo: "Federación",
    subtitulo: "Termas de Entre Ríos · 8 días",
    destino: "Entre Ríos",
    categoria: "termas",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Clima Termal Suites",
    regimen: "Desayuno. Opcional MP en Los Pinos $99.999",
    excursiones: ["Termas de Chajarí*", "Termas de Concepción*", "Visita a fábrica de alfajores"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "22 Ago 2026", estado: "disponible" },
      { fecha: "26 Sep 2026", estado: "disponible" },
      { fecha: "17 Oct 2026", estado: "disponible" },
      { fecha: "31 Oct 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["* No incluye entrada"],
    precio: 459999,
    precioCama: 489999,
    precioCuadruple: 399999,
    precioCuadrupleCama: 429999,
    base: "doble",
    sellos: ["viaja-solo", "family-plan"],
    color: "#B8451F",
    foto: "federacion",
    temporadas: ["agosto-diciembre", "escapadas"],
  },
  {
    id: "federacion-low-cost-agosto",
    titulo: "Federación · Super Promo Low Cost",
    subtitulo: "Termas de Entre Ríos · base cuádruple",
    destino: "Entre Ríos",
    categoria: "termas",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Clima Termal Suites",
    regimen: "Desayuno. Opcional MP en Los Pinos $99.999",
    excursiones: ["Termas de Chajarí*", "Termas de Concepción*", "Visita a fábrica de alfajores"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "06 Ago 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa Low Cost en base cuádruple · cupos limitados", "* No incluye entrada"],
    precio: 299999,
    precioCama: 329999,
    base: "cuádruple",
    sellos: ["low-cost", "viaja-solo"],
    destacado: "Tarifa más baja del año",
    color: "#C81E6E",
    foto: "federacion",
    temporadas: ["agosto-diciembre", "escapadas", "promociones"],
  },
  {
    id: "san-juan-talampaya",
    titulo: "San Juan · Talampaya · Valle de la Luna",
    subtitulo: "Parques Nacionales y bodega",
    destino: "San Juan · La Rioja",
    categoria: "sierras",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel Albertina (San Juan) + 2n Hotel Cuesta de Miranda (Villa Unión)",
    regimen: "Media pensión",
    excursiones: ["Visita a bodega en San Juan", "Parque Nacional Talampaya", "Parque Provincial Ischigualasto (Valle de la Luna)"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [{ fecha: "04 Sep 2026", estado: "disponible" }],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    precio: 749999,
    precioCama: 769999,
    base: "doble",
    sellos: ["viaja-solo"],
    color: "#A24A1D",
    foto: "talampaya",
    temporadas: ["agosto-diciembre"],
  },
  {
    id: "smandes-bariloche",
    titulo: "San Martín de los Andes · Bariloche",
    subtitulo: "Ruta de los 7 Lagos",
    destino: "Patagonia · Neuquén · Río Negro",
    categoria: "sierras",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel Crismalu (SMAndes) + 3n Hotel Plaza / Concept (Bariloche)",
    regimen: "Media pensión",
    excursiones: ["Ruta Panorámica por 7 Lagos", "Villa La Angostura"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Benito Juárez", "Tres Arroyos", "Bahía Blanca"],
    salidas: [
      { fecha: "01 Nov 2026", estado: "disponible" },
      { fecha: "13 Dic 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 699999,
    precioCamaPromo: 729999,
    precio: 749999,
    precioCama: 779999,
    promo: "Pago contado",
    promoDescuento: "7% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "viaja-solo"],
    color: "#2C5876",
    foto: "bariloche",
    temporadas: ["agosto-diciembre", "promociones"],
  },
  {
    id: "bariloche-puertovaras",
    destinos: ["bariloche", "puerto-varas"],
    titulo: "Bariloche · Puerto Varas",
    subtitulo: "Argentina y Chile · Cruce a Patagonia chilena",
    destino: "Bariloche · Puerto Varas",
    categoria: "internacional",
    transporte: "bus",
    duracion: "8 días · 5 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "2n Hotel M383 (Bariloche) + 3n Hotel Borde Lago (Puerto Varas)",
    regimen: "Media pensión",
    excursiones: ["City Tour Puerto Varas", "La Angostura"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Benito Juárez", "Tres Arroyos", "Bahía Blanca"],
    salidas: [
      { fecha: "02 Oct 2026", estado: "disponible" },
      { fecha: "04 Nov 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica", "Tarifa promo aplica con pago total al reservar"],
    precioPromo: 799999,
    precioCamaPromo: 829999,
    precio: 849999,
    precioCama: 879999,
    promo: "Pago contado",
    promoDescuento: "6% OFF",
    base: "doble",
    sellos: ["tarifa-promo"],
    color: "#2C5876",
    foto: "puerto-varas",
    temporadas: ["agosto-diciembre", "promociones"],
  },
  {
    id: "catamarca-fiambala",
    titulo: "Catamarca · Termas de Fiambalá",
    subtitulo: "Ruta del Adobe · 7 días",
    destino: "Catamarca",
    categoria: "termas",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "1n Paraíso Arenales (Catamarca) + 2n San Francisco (Fiambalá) + 1n Belén",
    regimen: "Media pensión",
    excursiones: ["Termas de Fiambalá*", "Ruta del Adobe"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "13 Ago 2026", estado: "disponible" },
      { fecha: "09 Sep 2026", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar", "* No incluye entrada"],
    precioPromo: 799999,
    precioCamaPromo: 829999,
    precio: 899999,
    precioCama: 929999,
    promo: "Pago contado",
    promoDescuento: "11% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "viaja-solo"],
    color: "#A24A1D",
    foto: "catamarca",
    temporadas: ["agosto-diciembre", "promociones"],
  },

  // ============ FIESTAS 2026/2027 ============
  {
    id: "camboriu-navidad",
    destinos: ["camboriu", "federacion"],
    titulo: "Camboriú · Navidad",
    subtitulo: "Brasil para las fiestas",
    destino: "Balneario Camboriú · Brasil",
    categoria: "playa",
    transporte: "bus",
    duracion: "12 días · 7 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Hamburgo (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: ["Itajaí", "Florianópolis (centro)", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy", "Liniers", "Zárate"],
    salidas: [{ fecha: "27 Dic 2026", estado: "ultimos-cupos" }],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica"],
    precio: 1899999,
    precioCuadruple: 1749999,
    precioAntes: 2099999,
    base: "doble",
    sellos: ["ano-nuevo", "ultimos-cupos", "piscina-climatizada"],
    destacado: "Pasá Navidad y Año Nuevo en la playa",
    color: "#1B7A8E",
    foto: "camboriu",
    temporadas: ["fiestas", "brasil"],
  },
  {
    id: "cataratas-fin-de-ano",
    destinos: ["cataratas", "federacion"],
    titulo: "Cataratas · Posadas · Federación",
    subtitulo: "Fin de Año · Triple destino",
    destino: "Misiones · Entre Ríos",
    categoria: "cataratas",
    transporte: "bus",
    duracion: "8 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel El Carmen 3★",
    regimen: "Media pensión",
    excursiones: [
      "Ruinas de San Ignacio*", "Minas de Wanda*", "Cataratas Argentinas*", "Cataratas Brasileras*",
      "Aripuca*", "Yerbatera", "City Tour Puerto Iguazú + Hito 3 Fronteras",
      "Duty Free Shop", "Costanera de Posadas", "Full Day Termas de Federación*"
    ],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [{ fecha: "28 Dic 2026", estado: "disponible" }],
    incluye: ["Cena Show en Posadas (al regreso)", "Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 699999,
    precioCamaPromo: 729999,
    precio: 729999,
    precioCama: 759999,
    promo: "Pago contado",
    promoDescuento: "4% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "ano-nuevo"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["fiestas", "promociones"],
  },

  // ============ ENERO - FEBRERO 2027 ============
  {
    id: "camboriu-enero",
    destinos: ["camboriu", "federacion"],
    titulo: "Camboriú con Federación",
    subtitulo: "Verano en Brasil · Clásico 7 noches",
    destino: "Balneario Camboriú · Brasil",
    categoria: "playa",
    transporte: "bus",
    duracion: "12 días · 7 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Hamburgo (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: ["Itajaí", "Florianópolis (centro)", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy", "Liniers", "Zárate"],
    salidas: [
      { fecha: "11 Ene 2027", estado: "disponible" },
      { fecha: "25 Ene 2027", estado: "disponible" },
      { fecha: "08 Feb 2027", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica"],
    precio: 1599999,
    precioTriple: 1499999,
    precioCuadruple: 1399999,
    base: "doble",
    sellos: ["family-plan", "piscina-climatizada"],
    color: "#1B7A8E",
    foto: "camboriu",
    temporadas: ["verano", "brasil"],
  },
  {
    id: "cataratas-verano",
    destinos: ["cataratas", "federacion"],
    titulo: "Cataratas · Posadas · Federación",
    subtitulo: "Verano · Triple destino",
    destino: "Misiones · Entre Ríos",
    categoria: "cataratas",
    transporte: "bus",
    duracion: "8 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel El Carmen 3★",
    regimen: "Media pensión",
    excursiones: [
      "Ruinas de San Ignacio*", "Minas de Wanda*", "Cataratas Argentinas*", "Cataratas Brasileras*",
      "Aripuca*", "Yerbatera", "City Tour Puerto Iguazú + Hito 3 Fronteras",
      "Duty Free Shop", "Costanera de Posadas", "Full Day Termas de Federación*"
    ],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "03 Ene 2027", estado: "disponible" },
      { fecha: "24 Ene 2027", estado: "disponible" },
      { fecha: "03 Feb 2027", estado: "disponible" },
    ],
    incluye: ["Cena Show en Posadas (al regreso)", "Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 699999,
    precioCamaPromo: 729999,
    precio: 749999,
    precioCama: 779999,
    promo: "Pago contado",
    promoDescuento: "7% OFF",
    base: "doble",
    sellos: ["tarifa-promo"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["verano", "promociones"],
  },
  {
    id: "carlos-paz-verano",
    titulo: "Villa Carlos Paz",
    subtitulo: "Verano en las sierras",
    destino: "Córdoba",
    categoria: "sierras",
    transporte: "bus",
    duracion: "7 días · 4 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Embajador (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: ["Cosquín y La Falda", "Visita a fábrica de alfajores", "Córdoba Capital"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Olavarría", "Bolívar", "9 de Julio", "Junín"],
    salidas: [
      { fecha: "17 Ene 2027", estado: "disponible" },
      { fecha: "21 Feb 2027", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Tarifa promo aplica con pago total al reservar"],
    precioPromo: 529999,
    precioCamaPromo: 559999,
    precio: 569999,
    precioCama: 599999,
    promo: "Pago contado",
    promoDescuento: "7% OFF",
    base: "doble",
    sellos: ["tarifa-promo", "piscina-climatizada"],
    color: "#446B2E",
    foto: "carlospaz",
    temporadas: ["verano", "promociones"],
  },

  // ============ AÉREAS NACIONALES 2026 ============
  {
    id: "cataratas-aereo-agosto-octubre",
    titulo: "Cataratas en Aéreo",
    subtitulo: "JetSmart · 5 días",
    destino: "Puerto Iguazú",
    categoria: "aereos",
    transporte: "aereo",
    aerolinea: "JetSmart",
    duracion: "5 días · 4 noches",
    hotel: "Hotel Carmen — Puerto Iguazú",
    regimen: "Media pensión",
    excursiones: ["Cataratas Argentinas*", "Cataratas Brasileras*", "Aripuca*", "City Tour Puerto Iguazú", "Duty Free Shop"],
    embarques: ["Vuelo JetSmart desde Buenos Aires (Carry On 8kg + Mochila 3kg)", "Opcional traslado desde MdP/Tandil/Azul/Olav/Bolívar $180.000"],
    salidas: [
      { fecha: "17 Ago 2026", estado: "disponible" },
      { fecha: "31 Ago 2026", estado: "disponible" },
      { fecha: "14 Sep 2026", estado: "disponible" },
      { fecha: "28 Sep 2026", estado: "disponible" },
      { fecha: "12 Oct 2026", estado: "disponible" },
    ],
    incluye: ["Vuelos JetSmart", "Traslado aeropuerto/hotel/aeropuerto", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques", "* No incluye entrada"],
    precio: 699999,
    base: "doble",
    sellos: ["cupos-confirmados"],
    color: "#0F6E3F",
    foto: "cataratas",
    temporadas: ["agosto-diciembre", "aereos-nacionales"],
  },
  {
    id: "salta-aereo-agosto-octubre",
    titulo: "Salta en Aéreo",
    subtitulo: "Aerolíneas Argentinas · 5 días",
    destino: "Salta",
    categoria: "aereos",
    transporte: "aereo",
    aerolinea: "Aerolíneas Argentinas",
    duracion: "5 días · 4 noches",
    hotel: "Hotel Las Vegas — Salta",
    regimen: "Desayuno",
    excursiones: ["City Tour Salta"],
    embarques: ["Vuelo desde Buenos Aires (Carry On 8kg + Mochila 3kg)", "Opcional traslado desde MdP/Tandil/Azul/Olav/Bolívar $180.000"],
    salidas: [
      { fecha: "24 Ago 2026", estado: "disponible" },
      { fecha: "07 Sep 2026", estado: "disponible" },
      { fecha: "21 Sep 2026", estado: "disponible" },
      { fecha: "05 Oct 2026", estado: "disponible" },
      { fecha: "19 Oct 2026", estado: "disponible" },
    ],
    incluye: ["Vuelos Aerolíneas Argentinas", "Traslado aeropuerto/hotel/aeropuerto", "Asistencia Médica Avril sin límite de edad"],
    notas: ["No incluye entradas a parques"],
    precio: 649999,
    base: "doble",
    sellos: ["cupos-confirmados"],
    color: "#B8451F",
    foto: "salta",
    temporadas: ["agosto-diciembre", "aereos-nacionales"],
  },
  {
    id: "mendoza-aereo-junio",
    titulo: "Mendoza en Aéreo",
    subtitulo: "Vuelo + hotel + bodegas · Cupos confirmados",
    destino: "Mendoza",
    categoria: "aereos",
    transporte: "aereo",
    aerolinea: "Aerolíneas Argentinas",
    duracion: "5 días · 4 noches",
    hotel: "Hotel Cordón del Plata — Mendoza",
    regimen: "Desayuno",
    excursiones: ["City Tour Mendoza", "Visita a bodega"],
    embarques: ["Vuelo desde Buenos Aires (Carry On 8kg + Mochila 3kg)", "Opcional traslado desde MdP/Tandil/Azul/Olav/Bolívar $180.000"],
    salidas: [
      { fecha: "12 Jun 2026", estado: "ultimos-cupos" },
    ],
    incluye: ["Vuelos Aerolíneas Argentinas", "Traslado aeropuerto/hotel/aeropuerto", "Asistencia Médica Avril sin límite de edad"],
    notas: ["Cupos confirmados con la aerolínea"],
    precio: 499999,
    precioAntes: 569999,
    base: "doble",
    urgenciaTexto: "Últimos 2 lugares",
    sellos: ["ultimos-cupos", "cupos-confirmados"],
    destacado: "Cupos confirmados",
    color: "#7C2418",
    foto: "mendoza",
    temporadas: ["mayo-junio-26", "aereos-nacionales"],
  },

  // ============ AÉREO INTERNACIONAL ============
  {
    id: "europa-sonada-octubre",
    titulo: "Europa Soñada",
    subtitulo: "Mi primer viaje a Europa · 5 países",
    destino: "España · Italia · Francia · Suiza · Austria",
    categoria: "internacional",
    transporte: "aereo",
    aerolinea: "Iberia · vuelo directo Ezeiza-Madrid",
    duracion: "19 días · 17 noches",
    hotel: "Barcelona · Costa Azul · Roma · Florencia · Venecia · Innsbruck · Zurich · París · Lourdes · Madrid",
    regimen: "Desayuno",
    excursiones: [
      "Visitas con guía local en Barcelona, Madrid, Roma, Florencia, Venecia, Innsbruck y París",
      "Recorrido nocturno por Madrid y París",
      "Coordinador experto desde tu ciudad",
      "Guía acompañante durante todo el recorrido",
    ],
    excursionesOpcionales: [
      "Cena de Tapas en Madrid",
      "Almuerzo en Toledo, Pisa, Roma",
      "Cena en Florencia, Lourdes",
      "Cena con espectáculo folklore tirolés en Innsbruck",
      "Vaticano: museos y Capilla Sixtina",
      "Paseo en Góndola en Venecia",
      "Paseo en Bateaux Mouche en París",
      "Subida a la Torre Eiffel (2° piso)",
    ],
    excursionesOpcionalesUSD: 500,
    embarques: ["Traslado en bus desde MdP, Balcarce, Tandil, Azul, Saladillo al aeropuerto incluido"],
    salidas: [
      { fecha: "05 Oct 2026", estado: "cupos-confirmados", detalle: "Vuelo IB 106 17:50 hs · Llega 06 Oct" },
    ],
    incluye: [
      "Pasaje aéreo Iberia desde Ezeiza",
      "Traslados aeropuerto/hotel en Barcelona y Madrid",
      "Asistencia Avril hasta 75 años",
      "Kit de viaje",
      "Último día libre en Madrid",
    ],
    vuelosDetalle: [
      "IDA · IB 106 — 05/10 — Ezeiza 17:50 → Madrid 10:45 (06/10)",
      "IB 413 — 06/10 — Madrid 12:40 → Barcelona 14:00",
      "VUELTA · IB 107 — 23/10 — Madrid 12:15 → Ezeiza 19:55",
    ],
    precioUSD: 4190,
    impuestosUSD: 990,
    cityTaxUSD: 90,
    base: "doble",
    sellos: ["bestseller", "cupos-confirmados"],
    destacado: "Cupos confirmados · 1 valija 23kg incluida",
    color: "#1B3D6B",
    foto: "europa",
    temporadas: ["agosto-diciembre", "europa"],
  },

  // ============ MARZO - ABRIL 2027 ============
  {
    id: "camboriu-marzo-abril",
    destinos: ["camboriu", "federacion"],
    titulo: "Camboriú con Federación",
    subtitulo: "Clásico 7 noches · Marzo / Abril 2027",
    destino: "Balneario Camboriú · Brasil",
    categoria: "playa",
    transporte: "bus",
    duracion: "12 días · 7 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Hamburgo (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: ["Itajaí", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [
      { fecha: "02 Mar 2027", estado: "disponible" },
      { fecha: "15 Mar 2027", estado: "disponible" },
      { fecha: "19 Abr 2027", estado: "disponible" },
    ],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica"],
    precio: 1299999,
    precioCama: 1349999,
    precioTriple: 1249999,
    precioCuadruple: 1199999,
    base: "doble",
    sellos: ["family-plan", "piscina-climatizada"],
    color: "#1B7A8E",
    foto: "camboriu",
    temporadas: ["marzo-abril-27", "brasil"],
  },
  {
    id: "camboriu-especial-abril",
    destinos: ["camboriu", "federacion"],
    titulo: "Camboriú · Especial 10 noches",
    subtitulo: "15 días · Para los que quieren disfrutar más",
    destino: "Balneario Camboriú · Brasil",
    categoria: "playa",
    transporte: "bus",
    duracion: "15 días · 10 noches",
    bus: "Mix (Semicama / Coche Cama)",
    hotel: "Hotel Hamburgo (Piscina climatizada)",
    regimen: "Media pensión",
    excursiones: ["Itajaí", "Termas de Federación al regreso*"],
    embarques: ["Mar del Plata", "Balcarce", "Tandil", "Azul", "Saladillo", "Chivilcoy"],
    salidas: [{ fecha: "04 Abr 2027", estado: "disponible" }],
    incluye: ["Cena a bordo con bebidas (ida)", "Snack y refrigerio"],
    notas: ["No incluye asistencia médica"],
    precio: 1499999,
    precioCama: 1549999,
    precioTriple: 1449999,
    precioCuadruple: 1399999,
    base: "doble",
    sellos: ["family-plan", "piscina-climatizada"],
    destacado: "10 noches en Camboriú",
    color: "#1B7A8E",
    foto: "camboriu",
    temporadas: ["marzo-abril-27", "brasil"],
  },
];

// ============ TEMPORADAS ============
window.NT_TEMPORADAS = [
  {
    id: "mayo-junio-26",
    nombre: "Mayo · Junio 2026",
    cuando: "MAY · JUN",
    anio: "2026",
    eyebrow: "Próximas salidas",
    subtitulo: "Salidas inmediatas · escapadas de otoño",
    icon: "☂",
    color: "#7C2418",
    bgColor: "#F2DCD9",
  },
  {
    id: "vacaciones-invierno",
    nombre: "Vacaciones de Invierno",
    cuando: "JULIO",
    anio: "2026",
    eyebrow: "Julio 2026",
    subtitulo: "Receso escolar · Cupos confirmados",
    icon: "❄",
    color: "#1B5E8C",
    bgColor: "#E8F1F7",
  },
  {
    id: "finde-xl",
    nombre: "Findes XL",
    cuando: "FINDES",
    anio: "Feriados",
    eyebrow: "4 a 5 días",
    subtitulo: "Escapadas para feriados puente",
    icon: "⚡",
    color: "#B8451F",
    bgColor: "#F7E8DD",
  },
  {
    id: "escapadas",
    nombre: "Escapadas",
    cuando: "ESCAPADAS",
    anio: "Todo el año",
    eyebrow: "Hasta 8 días",
    subtitulo: "Para cortar la rutina sin pedir vacaciones",
    icon: "✺",
    color: "#446B2E",
    bgColor: "#EAF1DD",
  },
  {
    id: "agosto-diciembre",
    nombre: "Agosto a Diciembre",
    cuando: "AGO → DIC",
    anio: "2026",
    eyebrow: "Primavera 2026",
    subtitulo: "Floración, días largos y mejores precios",
    icon: "✿",
    color: "#0F6E3F",
    bgColor: "#DDEDE3",
  },
  {
    id: "brasil",
    nombre: "Brasil",
    cuando: "JUL · ENE",
    anio: "Brasil",
    eyebrow: "Camboriú, Foz, Florianópolis",
    subtitulo: "Playa, fiesta y caipirinhas · bus o avión",
    icon: "☼",
    color: "#1B7A8E",
    bgColor: "#DCEDF1",
  },
  {
    id: "europa",
    nombre: "Europa",
    cuando: "OCTUBRE",
    anio: "2026",
    eyebrow: "Aéreos · 19 días · 5 países",
    subtitulo: "Iberia desde Ezeiza · cupos confirmados",
    icon: "♛",
    color: "#1B3D6B",
    bgColor: "#DEE6F0",
  },
  {
    id: "aereos-nacionales",
    nombre: "Aéreos Nacionales",
    cuando: "AÉREOS",
    anio: "Todo el año",
    eyebrow: "Vuelo + hotel + traslados",
    subtitulo: "Cataratas y Salta desde Buenos Aires",
    icon: "✈",
    color: "#A36B2E",
    bgColor: "#F5EDDD",
  },
  {
    id: "fiestas",
    nombre: "Fiestas 26/27",
    cuando: "DIC · ENE",
    anio: "26 / 27",
    eyebrow: "Navidad y Año Nuevo",
    subtitulo: "Pasá las fiestas en la playa",
    icon: "✦",
    color: "#FFD23F",
    bgColor: "#FFF6D6",
  },
  {
    id: "verano",
    nombre: "Verano 2027",
    cuando: "ENE · FEB",
    anio: "2027",
    eyebrow: "Enero · Febrero",
    subtitulo: "Brasil, Cataratas, Carlos Paz",
    icon: "☀",
    color: "#ED1C24",
    bgColor: "#FBE2E3",
  },
  {
    id: "marzo-abril-27",
    nombre: "Marzo · Abril 2027",
    cuando: "MAR · ABR",
    anio: "2027",
    eyebrow: "Otoño 27",
    subtitulo: "Camboriú especial · 7 o 10 noches",
    icon: "☘",
    color: "#1B7A8E",
    bgColor: "#DCEDF1",
  },
];

window.NT_PROMOS_DESTACADAS = [
  {
    id: "promo-pago-contado",
    titulo: "Pago contado",
    descuento: "Hasta 11% OFF",
    descripcion: "Abonando el total en una sola vez accedés a la tarifa promo en paquetes seleccionados.",
    cta: "Ver paquetes con promo",
    color: "#ED1C24",
  },
  {
    id: "promo-cuotas",
    titulo: "Cuotas sin interés",
    descuento: "Sin tarjeta",
    descripcion: "Tenemos nuestra app de autogestión: te armamos un plan de pago y pagás cuota a cuota con QR o en la oficina.",
    cta: "Cómo funciona",
    color: "#1A1410",
    targetId: "magnus",
  },
  {
    id: "promo-viaja-solo",
    titulo: "Viajás solo · igual tarifa",
    descuento: "Sin suplemento",
    descripcion: "Compartiendo habitación pagás la base doble. Nadie viaja solo en New Trips.",
    cta: "Ver paquetes ideales",
    color: "#446B2E",
  },
  {
    id: "promo-family",
    titulo: "Family Plan",
    descuento: "Menores con descuento",
    descripcion: "Hasta 50% OFF para chicos hasta 5 años compartiendo habitación con 2 adultos.",
    cta: "Paquetes con Family Plan",
    color: "#1B7A8E",
  },
  {
    id: "promo-2x1",
    titulo: "2do pasajero 50% OFF",
    descuento: "50% OFF",
    descripcion: "Salida Cataratas + Posadas + Federación de Junio: 2do pasajero la mitad.",
    cta: "Ver salida",
    color: "#FFD23F",
  },
  {
    id: "promo-3x2",
    titulo: "Viajan 3, pagan 2",
    descuento: "1 viaja gratis",
    descripcion: "Mendoza · Cacheuta · San Rafael salida de Junio: vienen 3, pagan 2.",
    cta: "Ver salida",
    color: "#7C2418",
  },
];

window.NT_CATEGORIES = [
  { id: "todos", nombre: "Todos", icon: "🌎" },
  { id: "termas", nombre: "Termas", icon: "♨" },
  { id: "sierras", nombre: "Sierras", icon: "⛰" },
  { id: "playa", nombre: "Playa", icon: "🌊" },
  { id: "cataratas", nombre: "Cataratas", icon: "💧" },
  { id: "internacional", nombre: "Internacional", icon: "✈" },
  { id: "aereos", nombre: "Aéreos", icon: "🛫" },
];

window.NT_SELLOS = {
  "promo-2x1": { texto: "2do PAX 50% OFF", color: "#F2B5D4", textColor: "#1A1410" },
  "promo-2do-30": { texto: "2do PAX 30% OFF", color: "#F2B5D4", textColor: "#1A1410" },
  "viajan-4-pagan-3": { texto: "Viajan 3, pagan 2", color: "#FFD23F", textColor: "#1A1410" },
  "viaja-solo": { texto: "Viajás solo · igual tarifa", color: "#1A1410", textColor: "#FAF6EE" },
  "ultimos-cupos": { texto: "Últimos cupos", color: "#ED1C24", textColor: "#FFFFFF" },
  "casi-completa": { texto: "Salida casi completa", color: "#ED1C24", textColor: "#FFFFFF" },
  "cupos-confirmados": { texto: "Cupos confirmados ✓", color: "#0F6E3F", textColor: "#FFFFFF" },
  "tarifa-promo": { texto: "Promo pago contado", color: "#FFD23F", textColor: "#1A1410" },
  "oferta": { texto: "Oferta", color: "#D24A1F", textColor: "#FFFFFF" },
  "promo-puntual": { texto: "Promo", color: "#0F6E3F", textColor: "#FFFFFF" },
  "low-cost": { texto: "Super Promo Low Cost", color: "#C81E6E", textColor: "#FFFFFF" },
  "family-plan": { texto: "Family Plan", color: "#1A1410", textColor: "#FAF6EE" },
  "piscina-climatizada": { texto: "Piscina climatizada", color: "#1B7A8E", textColor: "#FFFFFF" },
  "pension-completa": { texto: "Pensión completa", color: "#446B2E", textColor: "#FFFFFF" },
  "ano-nuevo": { texto: "Fin de año", color: "#FFD23F", textColor: "#1A1410" },
  "bestseller": { texto: "Más vendido", color: "#1A1410", textColor: "#FFD23F" },
  "abiertas-reservas": { texto: "Reservas abiertas", color: "#FAF6EE", textColor: "#1A1410" },
  "disponible": { texto: "Cupos disponibles", color: "#0F6E3F", textColor: "#FFFFFF" },
};

window.NT_DIFERENCIALES = [
  { titulo: "Viajás solo, igual tarifa", subtitulo: "Compartiendo habitación pagás la base doble. Sin recargo por single.", icon: "solo" },
  { titulo: "Embarques en tu ciudad", subtitulo: "Mar del Plata, Tandil, Azul, Olavarría, Junín y muchas más, sin costo extra.", icon: "bus" },
  { titulo: "Cuotas sin tarjeta", subtitulo: "Plan de pago con nuestra app · pagás con QR o en efectivo en la oficina.", icon: "cuotas" },
  { titulo: "Sin sorpresas", subtitulo: "Precio publicado = precio final. Solo sumamos 1,5% admin.", icon: "check" },
  { titulo: "Servicio premium a bordo", subtitulo: "Cena con vino, snacks, infusiones, licores y películas.", icon: "copa" },
  { titulo: "Coordinador acompañante", subtitulo: "Experto desde tu ciudad hasta volver. No estás solo nunca.", icon: "guia" },
];

window.NT_FAQS = [
  { q: "¿Qué incluye el precio?", a: "Bus o avión ida y vuelta, hospedaje, régimen de comidas según paquete, excursiones incluidas según itinerario, asistencia médica Avril sin límite de edad y coordinador acompañante." },
  { q: "¿Cómo pago si no tengo tarjeta de crédito?", a: "Tenemos nuestra propia app de autogestión: te armamos un plan de pago a tu medida y figura cada cuota. Podés pagar con QR (Mercado Pago, Modo, etc.) desde el celu o en efectivo en nuestra oficina. No necesitás tarjeta." },
  { q: "¿Y si viajo solo?", a: "Pagás la misma tarifa que en base doble compartiendo habitación. Es nuestro diferencial más fuerte: nadie viaja solo en New Trips." },
  { q: "¿Desde dónde sale el bus?", a: "Pasamos por Mar del Plata, Balcarce, Tandil, Azul, Olavarría, Bolívar, 9 de Julio, Junín, Saladillo, Chivilcoy y otras ciudades del interior bonaerense según el destino." },
  { q: "¿Hay descuentos para chicos?", a: "Muchos paquetes tienen Family Plan: menores hasta 5 años con tarifa especial compartiendo habitación con 2 adultos." },
  { q: "¿Qué pasa si no me sale Iberia o se cancela mi vuelo?", a: "Para los aéreos internacionales contamos con cupos confirmados con la aerolínea. Si hubiera reprogramación o cancelación, te asistimos junto con la aerolínea para reubicarte en la próxima salida disponible." },
];
